AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Create resources to delete old Formstack forms and submissions on a daily basis, in compliance with GDPR.
Parameters:
  Stage:
    Description: Lambda stage.
    Type: String
    AllowedValues:
      - PROD # only PROD currently supported since there isn't a CODE Formstack environment
  FormstackAccountRef:
    Description: Reference for the Formstack account.
    Type: String
  FormstackAccountId:
    Description: Id of the Formstack account.
    Type: String
  FormstackAccessToken:
    Description: Used to authenticate against the Formstack API.
    Type: String
  FormstackEncryptionPassword:
    Description: Used to decrypt Formstack submissions.
    Type: String
  AlarmTopic:
    Description: ARN of SNS topic to send messages to when a Formstack alarm transitions to the Alarm state.
    Type: String
Resources:
  FormstackFormDeletionLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: delete-expired-formstack-data-dist
        Key: !Sub ${Stage}/delete-expired-formstack-data-lambdas/app.jar
      Description: Lambda to delete old Formstack forms
      Environment:
        Variables:
          FormstackAccountId: !Ref FormstackAccountId
          FormstackAccessToken: !Ref FormstackAccessToken
          FormstackEncryptionPassword: !Ref FormstackEncryptionPassword
          IsDryRun: true
          LogLevel: INFO
      Events:
        DailyInvocation:
          Type: Schedule
          Properties:
            Schedule: cron(0 10 * * ? *)
      FunctionName: !Sub formstack-form-deletion-lambda-${FormstackAccountRef}-PROD
      Handler: com.gu.formstack.handlers.FormstackFormDeletionHandler::handleRequest
      MemorySize: 256
      Runtime: java11
      Timeout: 900
  FormstackSubmissionDeletionLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: delete-expired-formstack-data-dist
        Key: !Sub ${Stage}/delete-expired-formstack-data-lambdas/app.jar
      Description: Lambda to delete old Formstack submissions
      Environment:
        Variables:
          FORMSTACK_ACCOUNT_ID: !Ref FormstackAccountId
          FORMSTACK_ACCESS_TOKEN: !Ref FormstackAccessToken
          FORMSTACK_ENCRYPTION_PASSWORD: !Ref FormstackEncryptionPassword
          IS_DRY_RUN: true
          LOG_LEVEL: INFO
      # We want to invoke the lambda(s) for deleting forms submissions after the lambda(s) for deleting forms,
      # since this will save on API requests to get and delete submissions.
      Events:
        DailyInvocation:
          Type: Schedule
          Properties:
            Schedule: cron(0 11 * * ? *)
      FunctionName: !Sub formstack-submission-deletion-lambda-${FormstackAccountRef}-PROD
      Handler: com.gu.formstack.handlers.FormstackSubmissionDeletionHandler::handleRequest
      MemorySize: 256
      Runtime: java11
      Timeout: 900
  FormstackFormDeletionLambdaAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref AlarmTopic
      AlarmDescription: Alarm if all lambda invocations within the day fail, or if there are no invocations.
      AlarmName: !Sub formstack-form-deletion-lambda-alarm-${FormstackAccountRef}
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Metrics:
        - Id: invocations
          Label: Lambda invocations
          MetricStat:
            Metric:
              Dimensions:
                - Name: FunctionName
                  Value: !Ref FormstackFormDeletionLambda
              MetricName: Invocations
              Namespace: AWS/Lambda
            Period: 86400
            Stat: Sum
            Unit: Count
          ReturnData: False
        - Id: errors
          Label: Lambda errors
          MetricStat:
            Metric:
              Dimensions:
                - Name: FunctionName
                  Value: !Ref FormstackFormDeletionLambda
              MetricName: Errors
              Namespace: AWS/Lambda
            Period: 86400
            Stat: Sum
            Unit: Count
          ReturnData: False
        - Expression: errors / invocations
          Id: error_rate
          Label: Lambda error rate
          ReturnData: True
      Threshold: 1
      # Treat missing data as breaching so the alarm will trigger if the lambda isn't invoked for a given day.
      TreatMissingData: breaching
  FormstackSubmissionDeletionLambdaAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref AlarmTopic
      AlarmDescription: Alarm if all lambda invocations within the day fail, or if there are no invocations.
      AlarmName: !Sub formstack-submission-deletion-lambda-alarm-${FormstackAccountRef}
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Metrics:
        - Id: invocations
          Label: Lambda invocations
          MetricStat:
            Metric:
              Dimensions:
                - Name: FunctionName
                  Value: !Ref FormstackSubmissionDeletionLambda
              MetricName: Invocations
              Namespace: AWS/Lambda
            Period: 86400
            Stat: Sum
            Unit: Count
          ReturnData: False
        - Id: errors
          Label: Lambda errors
          MetricStat:
            Metric:
              Dimensions:
                - Name: FunctionName
                  Value: !Ref FormstackSubmissionDeletionLambda
              MetricName: Errors
              Namespace: AWS/Lambda
            Period: 86400
            Stat: Sum
            Unit: Count
          ReturnData: False
        - Expression: errors / invocations
          Id: error_rate
          Label: Lambda error rate
          ReturnData: True
      Threshold: 1
      # Treat missing data as breaching so the alarm will trigger if the lambda isn't invoked for a given day.
      TreatMissingData: breaching