#!/usr/bin/env bash

if ! java_11_home=$(/usr/libexec/java_home -v11); then
  echo "can't find Java 11 home; is it installed?"
fi

echo "exporting JAVA_HOME variable as $java_11_home"
export JAVA_HOME=$java_11_home