#!/usr/bin/env bash

set -e

root_dir="$( cd "$(dirname "$0")/.." || exit; pwd -P )"

install_requirements() {
  echo "installing requirements from Brewfile"
  brew bundle
}

set_java_home() {
  source "$root_dir/scripts/java_11_home"
}

build_local_code_uri() {
  docker build -t local-code-uri "$root_dir/scripts/local-code-uri"
}

main() {
  install_requirements
  set_java_home
  build_local_code_uri
}

main
